#!/bin/sh
localcompile() {
	sudo mkdir -p develop
	sudo mkdir -p bin
	sudo cp -r bin src include data LICENSE.txt project.manifest README.md develop/
	sudo docker run -it --rm --volume ./develop:/home/kipr:rw sillyfreak/wombat-cross \
	aarch64-linux-gnu-g++ -std=c++17 -g -Wall -I./include/* -I/usr/local/include/include/ -L/usr/local/lib ./src/*.cpp -lm -lz -lpthread -lkipr -o ./bin/botball_user_program
	sudo cp develop/bin/botball_user_program bin/
	sudo rm -rf develop
}
copy() {
	ping -c 1 192.168.125.1 > /dev/null || { echo "Host unreachable"; return 1; }
	if scp -r -q * "kipr@192.168.125.1:~/Documents/KISS/$1"; then
		return 0;
	else
	return 1;
	fi
}

shell() {
	ssh kipr@192.168.125.1
}

compile() {
	if [ -z "$1" ]; then
		echo "No destination specified.";
		return 1;
	fi
	echo "Compiling...";
	if wombatcompile; then
		if [[ "$1" != "-nocopy" ]]; then
			if copy "$1"; then
				echo -n "Succeeded at: "
			else
				echo -n "Copy failed at: "
			fi
		else
			echo -n "Compilation succeeded at: "
		fi
	else
		[ -d develop ] && rm -r develop
		echo -n "Compilation failed at: "
	fi
	date +"%r"
}
