#!/bin/sh
copy() {
    ping -c 1 192.168.125.1 > /dev/null || { echo "Host unreachable"; return 1; }
    if scp -r -q * "kipr@192.168.125.1:~/Documents/KISS/$1"; then
        return 0;
    else
	return 1;
    fi
}

shell() {
    ssh kipr@192.168.125.1
}

compile() {
	if [ -z "$1" ]; then
		echo "No destination specified.";
		return 1;
	fi
	echo "Compiling...";
    if wombatcompile; then
        if copy "$1"; then
            echo -n "Succeeded at: "
        else
            echo -n "Copy failed at: "
        fi
    else
        [ -d develop ] && rm -r develop
        echo -n "Compilation failed at: "
    fi
    date +"%r"
}
