name: C++ Compilation Check

on:
  pull_request:
    branches:
      - Eden

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (if any)
        run: sudo apt-get update && sudo apt-get install -y build-essential 'aarch64-linux-gnu-g+++'

      - name: Compile C++ code
        run: |
          $ aarch64-linux-gnu-g++ -Iinclude/* -I" \
          /usr/local/include/include" \
          -Wall src/*.cpp -L"/usr/local/lib" \
          -lkipr -lm -o "bin/botball_user_program" \
          -lz -lpthread
